name: axon
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind cppcheck

      - name: Static Code Analysis
        run: cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Build (Debug)
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build

      - name: Test (ASan/UBSan)
        run: cd build && ctest --output-on-failure

      - name: Build (Release)
        run: cmake -B build-release -DCMAKE_BUILD_TYPE=Release && cmake --build build-release

      - name: Valgrind
        run: |
          valgrind \
            --leak-check=full \
            --error-exitcode=1 \
            --track-origins=yes \
            ./build-release/tests/axon_tests